// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eejxmfvjlrrtnzaqhlfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlanhtZnZqbHJydG56YXFobGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDY2ODUsImV4cCI6MjA2NDMyMjY4NX0.ZprNNLwrXAUub8-2WCbhQLCBSTNStRZDjNVRgxn1tzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);